export CUDA_VISIBLE_DEVICES=3,4
accelerate launch --config_file /home/harry/BLIRL/SSL_Applications/Dreambooth/version_2/accelerate_config.yaml --main_process_port 1234 dreambooth.py \
--pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" \
--pretrained_vae_name_or_path="stabilityai/sd-vae-ft-mse"  \
--output_dir "/data1/StableDiffusion/Dreambooth/rick/prof_li"  \
--revision="fp16" \
--logging_dir "/data1/StableDiffusion/Dreambooth/rick/log10k" \
--with_prior_preservation  \
--prior_loss_weight=1.0 \
--mixed_precision="fp16" \
--seed=1337 \
--resolution=512 \
--train_batch_size=4 \
--train_text_encoder \
--gradient_accumulation_steps=1 \
--learning_rate=2e-6 \
--lr_scheduler="polynomial" \
--lr_warmup_steps=200 \
--num_class_images=200 \
--sample_batch_size=4 \
--max_train_steps=10000 \
--save_interval=10000 \
--save_sample_prompt="photo of zwx prof_li" \
--concepts_list="concepts_list_profli.json" \
